# Generated by Django 5.2.9 on 2026-03-04 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NESQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ADD_NAME", "Add Name")],
                        help_text="Type of entity operation to perform.",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Action-specific data structure, validated by Pydantic schema."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current workflow status of this queue item.",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this item was approved or rejected.",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the queue processor attempted this item.",
                        null=True,
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        help_text="Human-readable description of the requested change."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if processing failed.",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Processing result data on success (e.g., updated entity info).",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this item was submitted.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of the last modification."
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/moderator who approved or rejected this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nesq_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="User who submitted this request.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nesq_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NES Queue Item",
                "verbose_name_plural": "NES Queue Items",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["status"], name="nesq_status_idx")],
            },
        ),
    ]
