# Generated by Django 5.2.9 on 2026-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nesq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nesqueueitem",
            name="action",
            field=models.CharField(
                choices=[
                    ("ADD_NAME", "Add Name"),
                    ("CREATE_ENTITY", "Create Entity"),
                    ("UPDATE_ENTITY", "Update Entity"),
                ],
                help_text="Type of entity operation to perform.",
                max_length=20,
            ),
        ),
    ]
