# Generated by Django 5.2.9 on 2026-04-04 (rewritten)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseWorkflowRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique run identifier (auto-generated UUID)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        db_index=True,
                        help_text="Jawafdehi Case.case_id (e.g. case-abc123)",
                        max_length=200,
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        db_index=True,
                        help_text="Workflow template ID (matches directory name under workflows/)",
                        max_length=100,
                    ),
                ),
                (
                    "case_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of PRD state and runtime metadata",
                    ),
                ),
                (
                    "work_dir",
                    models.CharField(
                        blank=True,
                        help_text="Absolute path to the working directory for this run",
                        max_length=500,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the workflow finished successfully",
                    ),
                ),
                (
                    "has_failed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the workflow terminated with a failure",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if has_failed is True",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution finished (success or failure)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Case Workflow Run",
                "verbose_name_plural": "Case Workflow Runs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case_id", "workflow_id"),
                        name="unique_case_workflow",
                    )
                ],
            },
        ),
    ]
