# Generated by Django 5.2.9 on 2026-05-04 23:41

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cases", "0019_add_publication_date_to_documentsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=120, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("source_type", models.CharField(default="document", max_length=80)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("storage_path", models.CharField(blank=True, max_length=1000)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True, related_name="knowledge_sources", to="auth.group"
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_knowledge_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_sources",
                        to="cases.case",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="knowledge.knowledgecollection",
                    ),
                ),
                (
                    "document_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_sources",
                        to="cases.documentsource",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_knowledge_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["collection__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("page_start", models.PositiveIntegerField(blank=True, null=True)),
                ("page_end", models.PositiveIntegerField(blank=True, null=True)),
                ("section_title", models.CharField(blank=True, max_length=300)),
                ("table_title", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ["source_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_model", models.CharField(max_length=255)),
                ("dimensions", models.PositiveIntegerField(default=0)),
                (
                    "vector",
                    pgvector.django.vector.VectorField(blank=True, null=True),
                ),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.knowledgechunk",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_id", "embedding_model"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "embedding_model"),
                        name="knowledge_unique_chunk_embedding_model",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["collection", "access_level", "is_active"],
                name="knowledge_k_collect_f8bf68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["checksum"], name="knowledge_k_checksu_13bd06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["source", "chunk_index"], name="knowledge_k_source__0aac5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["content_hash"], name="knowledge_k_content_6db3af_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("source", "chunk_index"),
                name="knowledge_unique_source_chunk_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("source", "content_hash"),
                name="knowledge_unique_source_content_hash",
            ),
        ),
    ]
