# Generated by Django 5.2.8 on 2025-11-26 01:39

import cases.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier shared across versions of the same case",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Version number, increments with each published update",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("CORRUPTION", "Corruption"),
                            ("PROMISES", "Broken Promises"),
                        ],
                        help_text="Type of case (corruption, broken promises, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current state in the workflow",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Case title", max_length=200)),
                (
                    "case_start_date",
                    models.DateField(
                        blank=True,
                        help_text="When the alleged incident began",
                        null=True,
                    ),
                ),
                (
                    "case_end_date",
                    models.DateField(
                        blank=True,
                        help_text="When the alleged incident ended",
                        null=True,
                    ),
                ),
                (
                    "alleged_entities",
                    cases.fields.EntityListField(
                        default=list,
                        help_text="List of entity IDs for entities being accused",
                    ),
                ),
                (
                    "related_entities",
                    cases.fields.EntityListField(
                        blank=True,
                        default=list,
                        help_text="List of entity IDs for related entities",
                    ),
                ),
                (
                    "locations",
                    cases.fields.EntityListField(
                        blank=True,
                        default=list,
                        help_text="List of location entity IDs",
                    ),
                ),
                (
                    "tags",
                    cases.fields.TextListField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Rich text description of the case"
                    ),
                ),
                (
                    "key_allegations",
                    cases.fields.TextListField(
                        blank=True,
                        default=list,
                        help_text="List of key allegation statements",
                    ),
                ),
                (
                    "timeline",
                    cases.fields.TimelineListField(
                        blank=True, default=list, help_text="List of timeline entries"
                    ),
                ),
                (
                    "evidence",
                    cases.fields.EvidenceListField(
                        blank=True,
                        default=list,
                        help_text="List of evidence entries with source references",
                    ),
                ),
                (
                    "versionInfo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version metadata tracking changes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contributors assigned to this case",
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case_id", "state", "version"],
                        name="cases_case_case_id_01ca3c_idx",
                    ),
                    models.Index(
                        fields=["state", "version"], name="cases_case_state_0b1ac4_idx"
                    ),
                ],
            },
        ),
    ]
