# Generated by Django 5.2.8 on 2025-11-15 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allegation",
            name="timeline",
        ),
        migrations.RemoveField(
            model_name="modification",
            name="actor",
        ),
        migrations.AddField(
            model_name="modification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("event", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "allegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timelines",
                        to="cases.allegation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "date"],
            },
        ),
    ]
