# Generated by Django 5.2.8 on 2025-11-26 01:44

import cases.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the source",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Source title", max_length=300)),
                ("description", models.TextField(help_text="Source description")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to the source",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "related_entity_ids",
                    cases.fields.EntityListField(
                        blank=True,
                        default=list,
                        help_text="List of entity IDs related to this source",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft deletion flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Case this source is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sources",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
