# Generated by Django 5.2.8 on 2025-11-27 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_alleged_entities_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsource",
            name="case",
        ),
        migrations.AddField(
            model_name="documentsource",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contributors assigned to manage this source",
                related_name="assigned_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
