# Generated by Django 5.2.8 on 2025-11-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_remove_timeline_event_timeline_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
