# Generated by Django 5.2.8 on 2025-11-29 06:06

from django.db import migrations, models


def migrate_entity_ids_to_jawafentity(apps, schema_editor):
    """
    Migrate existing entity_id strings to JawafEntity records.
    
    Creates JawafEntity records from entity IDs in:
    - Case.alleged_entities_old
    - Case.related_entities_old
    - Case.locations_old
    - DocumentSource.related_entity_ids_old
    
    Deduplicates entities by nes_id.
    """
    Case = apps.get_model('cases', 'Case')
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    JawafEntity = apps.get_model('cases', 'JawafEntity')
    
    # Dictionary to track created entities by nes_id to avoid duplicates
    entity_cache = {}
    
    def get_or_create_entity(nes_id):
        """Get or create a JawafEntity for the given nes_id."""
        if not nes_id or not nes_id.strip():
            return None
        
        nes_id = nes_id.strip()
        
        # Check cache first
        if nes_id in entity_cache:
            return entity_cache[nes_id]
        
        # Check if entity already exists in database
        try:
            entity = JawafEntity.objects.get(nes_id=nes_id)
            entity_cache[nes_id] = entity
            return entity
        except JawafEntity.DoesNotExist:
            pass
        
        # Create new entity
        entity = JawafEntity.objects.create(nes_id=nes_id)
        entity_cache[nes_id] = entity
        return entity
    
    # Migrate Case entities
    for case in Case.objects.all():
        # Migrate alleged_entities
        if case.alleged_entities_old:
            for entity_id in case.alleged_entities_old:
                entity = get_or_create_entity(entity_id)
                if entity:
                    case.alleged_entities.add(entity)
        
        # Migrate related_entities
        if case.related_entities_old:
            for entity_id in case.related_entities_old:
                entity = get_or_create_entity(entity_id)
                if entity:
                    case.related_entities.add(entity)
        
        # Migrate locations
        if case.locations_old:
            for entity_id in case.locations_old:
                entity = get_or_create_entity(entity_id)
                if entity:
                    case.locations.add(entity)
    
    # Migrate DocumentSource entities
    for source in DocumentSource.objects.all():
        if source.related_entity_ids_old:
            for entity_id in source.related_entity_ids_old:
                entity = get_or_create_entity(entity_id)
                if entity:
                    source.related_entities.add(entity)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_remove_case_add_contributors_to_documentsource"),
    ]

    operations = [
        # Step 1: Rename old fields to preserve data
        migrations.RenameField(
            model_name="documentsource",
            old_name="related_entity_ids",
            new_name="related_entity_ids_old",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="alleged_entities",
            new_name="alleged_entities_old",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="locations",
            new_name="locations_old",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="related_entities",
            new_name="related_entities_old",
        ),
        
        # Step 2: Create JawafEntity model
        migrations.CreateModel(
            name="JawafEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nes_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Entity ID from Nepal Entity Service (NES) database (unique)",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the entity (optional if nes_id is present, required otherwise)",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jawaf Entity",
                "verbose_name_plural": "Jawaf Entities",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("display_name__isnull", True),
                            ("nes_id__isnull", True),
                            _negated=True,
                        ),
                        name="jawafentity_must_have_nes_id_or_display_name",
                    )
                ],
            },
        ),
        
        # Step 3: Add new ManyToMany fields
        migrations.AddField(
            model_name="documentsource",
            name="related_entities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Entities related to this source",
                related_name="document_sources",
                to="cases.jawafentity",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="alleged_entities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Entities being accused",
                related_name="cases_as_alleged",
                to="cases.jawafentity",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Location entities",
                related_name="cases_as_location",
                to="cases.jawafentity",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="related_entities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related entities",
                related_name="cases_as_related",
                to="cases.jawafentity",
            ),
        ),
        
        # Step 4: Migrate data from old fields to new entities
        migrations.RunPython(
            migrate_entity_ids_to_jawafentity,
            reverse_code=migrations.RunPython.noop,
        ),
        
        # Step 5: Remove old fields
        migrations.RemoveField(
            model_name="documentsource",
            name="related_entity_ids_old",
        ),
        migrations.RemoveField(
            model_name="case",
            name="alleged_entities_old",
        ),
        migrations.RemoveField(
            model_name="case",
            name="locations_old",
        ),
        migrations.RemoveField(
            model_name="case",
            name="related_entities_old",
        ),
    ]
