# Generated by Django 5.2.8 on 2025-11-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_evidence_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allegation",
            name="key_allegations",
            field=models.JSONField(default=list),
        ),
    ]
