# Generated by Django 5.2.8 on 2025-11-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_allegation_key_allegations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allegation",
            name="first_public_date",
        ),
        migrations.RemoveField(
            model_name="allegation",
            name="status",
        ),
        migrations.AddField(
            model_name="allegation",
            name="case_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="allegation",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under_review", "Under Review"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
