# Generated by Django 5.2.8 on 2025-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_add_jawafentity_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jawafentity",
            name="nes_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Entity ID from Nepal Entity Service (NES) database (unique)",
                max_length=300,
                null=True,
                unique=True,
            ),
        ),
    ]
