# Generated by Django 5.2.8 on 2025-11-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_remove_allegation_first_public_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modification",
            name="notes",
            field=models.TextField(),
        ),
    ]
