# Generated by Django 5.2.9 on 2025-12-07 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_jawafentity_nes_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file', upload_to='documents/%Y/%m/')),
                ('original_file_name', models.CharField(help_text='Original filename as uploaded', max_length=300)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='MIME type (e.g., application/pdf)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(help_text='The document source this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='cases.documentsource')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
