# Generated by Django 5.2.9 on 2025-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_jawafentity_nes_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("usability", "Usability Issue"),
                            ("content", "Content Feedback"),
                            ("general", "General Feedback"),
                        ],
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief summary of feedback", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed feedback description", max_length=5000
                    ),
                ),
                (
                    "related_page",
                    models.CharField(
                        blank=True,
                        help_text="Page or feature related to feedback",
                        max_length=300,
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional contact information",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        help_text="Current status of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of submitter (for rate limiting)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for administrators"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["feedback_type", "status"],
                        name="cases_feedb_feedbac_5eb8d3_idx",
                    ),
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="cases_feedb_status_1c4ad3_idx",
                    ),
                ],
            },
        ),
    ]
