# Generated by Django 5.2.9 on 2025-12-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the document', max_length=500),
        ),
    ]
