# Generated by Django 5.2.9 on 2026-01-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_case_image_fields'),
        ('cases', '0008_increase_url_max_length'),
    ]

    operations = [
    ]
