# Generated by Django 5.2.8 on 2025-11-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_create_contributor_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeline",
            name="allegation",
        ),
        migrations.AddField(
            model_name="allegation",
            name="evidence",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="allegation",
            name="timeline",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="Evidence",
        ),
        migrations.DeleteModel(
            name="Timeline",
        ),
    ]
