# Generated by Django 5.2.9 on 2026-01-11 09:07

from django.db import migrations, models


def migrate_url_to_urls(apps, schema_editor):
    """
    Migrate existing URL data from the old 'url' field to the new 'urls' JSONField.
    """
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    
    for source in DocumentSource.objects.all():
        if source.url:
            # Migrate single URL to list
            source.urls = [source.url]
        else:
            # If no URL exists, set to empty list (will need to be filled in by admin)
            source.urls = []
        source.save(update_fields=['urls'])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_merge_20260111_1452'),
    ]

    operations = [
        # First, add the new fields
        migrations.AddField(
            model_name='documentsource',
            name='urls',
            field=models.JSONField(default=list, help_text='List of URLs to the source (at least one required)'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher of the source', max_length=300),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Publication date of the source', max_length=100),
        ),
        # Migrate existing URL data to urls field
        migrations.RunPython(migrate_url_to_urls, reverse_code=migrations.RunPython.noop),
        # Remove the old url field
        migrations.RemoveField(
            model_name='documentsource',
            name='url',
        ),
    ]