# Generated by Django 5.2.9 on 2026-02-18 05:36

from django.db import migrations, models


def migrate_urls_to_list(apps, schema_editor):
    """
    Convert existing single URL strings to JSON lists.
    
    Raises ValueError if transformation fails to prevent silent data loss.
    """
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    db_alias = schema_editor.connection.alias
    
    import json
    
    for source in DocumentSource.objects.using(db_alias).all():
        url_value = source.url
        
        try:
            if url_value is None or url_value == '':
                source.url = '[]'
            elif isinstance(url_value, str):
                if url_value.startswith('['):
                    # Already JSON format, validate it
                    json.loads(url_value)
                    continue
                else:
                    # Convert single URL string to JSON array
                    source.url = json.dumps([url_value])
            else:
                # Unexpected type - fail loud
                raise ValueError(
                    f"DocumentSource {source.id} has unexpected url type: {type(url_value)}. "
                    f"Expected str or None, got {url_value!r}"
                )
            
            source.save(update_fields=['url'])
            
        except (json.JSONDecodeError, ValueError) as e:
            # Fail loud - do not silently skip or set to None
            raise ValueError(
                f"Failed to migrate url for DocumentSource {source.id} (source_id: {source.source_id}). "
                f"Original value: {url_value!r}. Error: {e}"
            ) from e


def reverse_urls_to_string(apps, schema_editor):
    """
    Convert URL lists back to single strings (for rollback).
    
    Raises ValueError if transformation fails.
    """
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    db_alias = schema_editor.connection.alias
    
    import json
    
    for source in DocumentSource.objects.using(db_alias).all():
        try:
            # Parse the JSON list
            if isinstance(source.url, str):
                url_list = json.loads(source.url)
            elif isinstance(source.url, list):
                url_list = source.url
            else:
                raise ValueError(
                    f"DocumentSource {source.id} has unexpected url type: {type(source.url)}. "
                    f"Expected str or list, got {source.url!r}"
                )
            
            # Take first URL or set to None
            source.url = url_list[0] if url_list else None
            source.save(update_fields=['url'])
            
        except (json.JSONDecodeError, ValueError) as e:
            raise ValueError(
                f"Failed to reverse url for DocumentSource {source.id} (source_id: {source.source_id}). "
                f"Original value: {source.url!r}. Error: {e}"
            ) from e


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_merge_20260112_0309'),
    ]

    operations = [
        # Convert existing string URLs to JSON format (atomic transaction)
        migrations.RunPython(
            migrate_urls_to_list, 
            reverse_urls_to_string,
            atomic=True
        ),
        # Change field type to JSONField
        migrations.AlterField(
            model_name='documentsource',
            name='url',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs for this source'),
        ),
    ]
