# Generated by Django 5.2.9 on 2026-02-18 05:36

from django.db import migrations, models


def convert_url_to_list(apps, schema_editor):
    """Convert existing single URL strings to lists."""
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    for source in DocumentSource.objects.all():
        if source.url and isinstance(source.url, str):
            # Convert single URL string to list
            source.url = [source.url] if source.url.strip() else []
            source.save(update_fields=['url'])
        elif source.url is None:
            # Convert None to empty list
            source.url = []
            source.save(update_fields=['url'])


def reverse_url_to_string(apps, schema_editor):
    """Convert URL lists back to single strings (for rollback)."""
    DocumentSource = apps.get_model('cases', 'DocumentSource')
    for source in DocumentSource.objects.all():
        if source.url and isinstance(source.url, list):
            # Take first URL from list, or None if empty
            source.url = source.url[0] if source.url else None
            source.save(update_fields=['url'])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_merge_20260112_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='url',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs for this source'),
        ),
        migrations.RunPython(convert_url_to_list, reverse_url_to_string),
    ]
