# Generated by Django 5.2.9 on 2026-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_change_url_to_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='source_type',
            field=models.CharField(choices=[('OFFICIAL_GOVERNMENT', 'Official (Government)'), ('MEDIA_NEWS', 'Media/News'), ('SOCIAL_MEDIA', 'Social Media'), ('INTERNAL_DOCUMENT', 'Internal Document'), ('ACADEMIC_RESEARCH', 'Academic/Research'), ('LEGAL_DOCUMENT', 'Legal Document'), ('WHISTLEBLOWER', 'Whistleblower'), ('OTHER', 'Other')], default='OTHER', help_text='Type of source', max_length=50),
        ),
    ]
