# Generated by Django 5.2.9 on 2026-01-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_add_multiple_urls_publisher_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='publication_date',
            field=models.CharField(blank=True, default='', help_text='Publication date of the source', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentsource',
            name='publisher',
            field=models.CharField(blank=True, default='', help_text='Publisher of the source', max_length=300),
        ),
    ]
