# Generated by Django 5.2.9 on 2026-03-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_source_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='source_type',
            field=models.CharField(blank=True, choices=[('LEGAL_COURT_ORDER', 'Legal: Court Order/Verdict'), ('LEGAL_PROCEDURAL', 'Legal: Procedural/Law Enforcement'), ('OFFICIAL_GOVERNMENT', 'Official (Government)'), ('FINANCIAL_FORENSIC', 'Financial/Forensic Record'), ('INTERNAL_CORPORATE', 'Internal Corporate Doc'), ('MEDIA_NEWS', 'Media/News'), ('INVESTIGATIVE_REPORT', 'Investigative Report'), ('PUBLIC_COMPLAINT', 'Public Complaint/Whistleblower'), ('LEGISLATIVE_DOC', 'Legislative/Policy Doc'), ('SOCIAL_MEDIA', 'Social Media'), ('OTHER_VISUAL', 'Other / Visual Assets')], help_text='Type of source', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CaseEntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accused', 'Accused'), ('related', 'Related')], help_text='Type of relationship (accused or related)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='The case in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='entity_relationships', to='cases.case')),
                ('entity', models.ForeignKey(help_text='The entity in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='case_relationships', to='cases.jawafentity')),
            ],
            options={
                'ordering': ['type', 'entity__display_name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='entities',
            field=models.ManyToManyField(help_text='Entities related to this case (accused or related)', related_name='cases', through='cases.CaseEntityRelationship', to='cases.jawafentity'),
        ),
        migrations.AddIndex(
            model_name='caseentityrelationship',
            index=models.Index(fields=['case', 'type'], name='cases_casee_case_id_d3a0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='caseentityrelationship',
            index=models.Index(fields=['entity', 'type'], name='cases_casee_entity__585d69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseentityrelationship',
            unique_together={('case', 'entity', 'type')},
        ),
    ]
