# Generated by Django 5.2.9 on 2026-03-10
# Unified migration for flexible entity-case relationships
# Combines alleged_entities and related_entities into single entities M2M field
# with CaseEntityRelationship through-model including type and notes fields

import django.db.models.deletion
from django.db import migrations, models


def migrate_entity_data_forward(apps, schema_editor):
    """
    Migrate data from old alleged_entities and related_entities M2M fields
    to new CaseEntityRelationship through model.
    """
    Case = apps.get_model('cases', 'Case')
    CaseEntityRelationship = apps.get_model('cases', 'CaseEntityRelationship')
    
    # Migrate alleged entities
    for case in Case.objects.all():
        for entity in case.alleged_entities.all():
            CaseEntityRelationship.objects.get_or_create(
                case=case,
                entity=entity,
                type='alleged'  # Use 'alleged' from the start
            )
    
    # Migrate related entities
    for case in Case.objects.all():
        for entity in case.related_entities.all():
            CaseEntityRelationship.objects.get_or_create(
                case=case,
                entity=entity,
                type='related'
            )


def migrate_entity_data_backward(apps, schema_editor):
    """
    Reverse migration: Copy data back from CaseEntityRelationship
    to alleged_entities and related_entities M2M fields.
    """
    Case = apps.get_model('cases', 'Case')
    CaseEntityRelationship = apps.get_model('cases', 'CaseEntityRelationship')
    
    # Restore alleged entities
    for relationship in CaseEntityRelationship.objects.filter(type='alleged'):
        relationship.case.alleged_entities.add(relationship.entity)
    
    # Restore related entities
    for relationship in CaseEntityRelationship.objects.filter(type='related'):
        relationship.case.related_entities.add(relationship.entity)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_source_type_field'),
    ]

    operations = [
        # Step 1: Create new CaseEntityRelationship model with notes field and all relationship types
        migrations.CreateModel(
            name='CaseEntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[
                        ('alleged', 'Alleged'),
                        ('related', 'Related'),
                        ('witness', 'Witness'),
                        ('opposition', 'Opposition'),
                        ('victim', 'Victim')
                    ],
                    max_length=20
                )),
                ('notes', models.CharField(
                    blank=True,
                    null=True,
                    help_text='Optional context about this entity\'s role (e.g., "Then president of XXX company")',
                    max_length=500
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_relationships', to='cases.case')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_relationships', to='cases.jawafentity')),
            ],
            options={
                'ordering': ['type', 'entity__display_name'],
            },
        ),
        
        # Step 2: Add new entities M2M field using through model
        migrations.AddField(
            model_name='case',
            name='entities',
            field=models.ManyToManyField(related_name='cases', through='cases.CaseEntityRelationship', to='cases.jawafentity'),
        ),
        
        # Step 3: Add indexes for performance
        migrations.AddIndex(
            model_name='caseentityrelationship',
            index=models.Index(fields=['case', 'type'], name='cases_casee_case_id_d3a0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='caseentityrelationship',
            index=models.Index(fields=['entity', 'type'], name='cases_casee_entity__585d69_idx'),
        ),
        
        # Step 4: Add unique constraint
        migrations.AlterUniqueTogether(
            name='caseentityrelationship',
            unique_together={('case', 'entity', 'type')},
        ),
        
        # Step 5: Migrate existing data from old fields to new table
        migrations.RunPython(migrate_entity_data_forward, migrate_entity_data_backward),
        
        # Step 6: Remove old M2M fields
        migrations.RemoveField(
            model_name='case',
            name='alleged_entities',
        ),
        migrations.RemoveField(
            model_name='case',
            name='related_entities',
        ),
    ]
