# Generated by Django 5.2.9 on 2026-03-22 20:59

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_deprecate_case_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="uploaded_content_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of uploaded file (e.g., application/pdf)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentsource",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded file (if source is from file upload)",
                null=True,
                upload_to="jawafdehi/sources/%Y/%m/%d/",
                validators=[
                    cases.models.validate_upload_file_extension,
                    cases.models.validate_upload_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="documentsource",
            name="uploaded_file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentsource",
            name="uploaded_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename for uploaded file",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                db_index=True,
                help_text="Stable unique identifier for this case",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes about the case (markdown supported)",
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEGAL_COURT_ORDER", "Legal: Court Order/Verdict"),
                    ("LEGAL_PROCEDURAL", "Legal: Procedural/Law Enforcement"),
                    ("OFFICIAL_GOVERNMENT", "Official (Government)"),
                    ("FINANCIAL_FORENSIC", "Financial/Forensic Record"),
                    ("INTERNAL_CORPORATE", "Internal Corporate Doc"),
                    ("MEDIA_NEWS", "Media/News"),
                    ("INVESTIGATIVE_REPORT", "Investigative Report"),
                    ("PUBLIC_COMPLAINT", "Public Complaint/Whistleblower"),
                    ("LEGISLATIVE_DOC", "Legislative/Policy Doc"),
                    ("SOCIAL_MEDIA", "Social Media"),
                    ("OTHER_VISUAL", "Other / Visual Assets"),
                ],
                help_text="Type of source",
                max_length=50,
                null=True,
            ),
        ),
    ]
