# Generated by Django 5.2.9 on 2026-03-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_add_case_entity_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='alleged_entities',
        ),
        migrations.RemoveField(
            model_name='case',
            name='related_entities',
        ),
    ]
