# Generated by Django 5.2.9 on 2026-03-17 13:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_case_entity_relationships(apps, schema_editor):
    """
    Backfill legacy Case M2M relationships into CaseEntityRelationship.

    Mappings:
    - alleged_entities -> relationship_type="alleged"
    - related_entities -> relationship_type="related"
    - locations -> relationship_type="related"
    """
    from django.db import connection

    Case = apps.get_model("cases", "Case")
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")

    table_names = set(connection.introspection.table_names())
    alleged_table_exists = "cases_case_alleged_entities" in table_names
    related_table_exists = "cases_case_related_entities" in table_names
    locations_table_exists = "cases_case_locations" in table_names

    if alleged_table_exists:
        for case in Case.objects.prefetch_related("alleged_entities"):
            for entity in case.alleged_entities.all():
                CaseEntityRelationship.objects.get_or_create(
                    case=case,
                    entity=entity,
                    relationship_type="alleged",
                    defaults={"notes": ""},
                )

    if related_table_exists:
        for case in Case.objects.prefetch_related("related_entities"):
            for entity in case.related_entities.all():
                CaseEntityRelationship.objects.get_or_create(
                    case=case,
                    entity=entity,
                    relationship_type="related",
                    defaults={"notes": ""},
                )

    if locations_table_exists:
        for case in Case.objects.prefetch_related("locations"):
            for entity in case.locations.all():
                CaseEntityRelationship.objects.get_or_create(
                    case=case,
                    entity=entity,
                    relationship_type="related",
                    defaults={"notes": ""},
                )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_deprecate_case_versioning"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseEntityRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("alleged", "Alleged"),
                            ("related", "Related"),
                            ("witness", "Witness"),
                            ("opposition", "Opposition"),
                            ("victim", "Victim"),
                        ],
                        help_text="Type of relationship between case and entity",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this relationship",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this relationship was created",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case this relationship belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_relationships",
                        to="cases.case",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="The entity involved in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_relationships",
                        to="cases.jawafentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Entity Relationship",
                "verbose_name_plural": "Case Entity Relationships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="unified_entities",
            field=models.ManyToManyField(
                help_text="All entities related to this case through the unified relationship system",
                related_name="unified_cases",
                through="cases.CaseEntityRelationship",
                to="cases.jawafentity",
            ),
        ),
        migrations.AddIndex(
            model_name="caseentityrelationship",
            index=models.Index(
                fields=["case", "relationship_type"], name="case_relationship_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseentityrelationship",
            index=models.Index(
                fields=["entity", "relationship_type"],
                name="entity_relationship_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseentityrelationship",
            constraint=models.UniqueConstraint(
                fields=("case", "entity", "relationship_type"),
                name="unique_case_entity_relationship_type",
            ),
        ),
        migrations.RunPython(
            backfill_case_entity_relationships,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RemoveField(
            model_name="case",
            name="alleged_entities",
        ),
        migrations.RemoveField(
            model_name="case",
            name="related_entities",
        ),
        migrations.RemoveField(
            model_name="case",
            name="locations",
        ),
    ]
