# Generated by Django 5.2.9 on 2026-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_deprecate_case_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="audit_notes",
            field=models.TextField(
                blank=True,
                help_text="Markdown-formatted audit trail documenting case history, editorial decisions, and source verification notes",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                db_index=True,
                help_text="Stable unique identifier for this case",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes about the case (markdown supported)",
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEGAL_COURT_ORDER", "Legal: Court Order/Verdict"),
                    ("LEGAL_PROCEDURAL", "Legal: Procedural/Law Enforcement"),
                    ("OFFICIAL_GOVERNMENT", "Official (Government)"),
                    ("FINANCIAL_FORENSIC", "Financial/Forensic Record"),
                    ("INTERNAL_CORPORATE", "Internal Corporate Doc"),
                    ("MEDIA_NEWS", "Media/News"),
                    ("INVESTIGATIVE_REPORT", "Investigative Report"),
                    ("PUBLIC_COMPLAINT", "Public Complaint/Whistleblower"),
                    ("LEGISLATIVE_DOC", "Legislative/Policy Doc"),
                    ("SOCIAL_MEDIA", "Social Media"),
                    ("OTHER_VISUAL", "Other / Visual Assets"),
                ],
                help_text="Type of source",
                max_length=50,
                null=True,
            ),
        ),
    ]
