# Generated by Django 6.0.3 on 2026-03-17 13:23

from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def migrate_existing_relationships(apps, schema_editor):
    """
    Copy existing alleged_entities and related_entities relationships
    to the new CaseEntityRelationship through-model.

    This migration preserves all existing data by:
    1. Copying alleged_entities with relationship_type="alleged"
    2. Copying related_entities with relationship_type="related"
    3. Using get_or_create to handle potential duplicates gracefully
    4. Gracefully handling cases where old ManyToMany tables don't exist
    """
    from django.db import connection

    Case = apps.get_model("cases", "Case")
    CaseEntityRelationship = apps.get_model("cases", "CaseEntityRelationship")

    # Track migration statistics
    alleged_migrated = 0
    related_migrated = 0
    duplicates_skipped = 0

    # Check if the old ManyToMany tables exist
    table_names = connection.introspection.table_names()
    alleged_table_exists = "cases_case_alleged_entities" in table_names
    related_table_exists = "cases_case_related_entities" in table_names

    print("Checking for existing data to migrate:")
    print(f"  - alleged_entities table exists: {alleged_table_exists}")
    print(f"  - related_entities table exists: {related_table_exists}")

    # Migrate alleged entities if table exists
    if alleged_table_exists:
        for case in Case.objects.prefetch_related("alleged_entities").all():
            for entity in case.alleged_entities.all():
                relationship, created = CaseEntityRelationship.objects.get_or_create(
                    case=case,
                    entity=entity,
                    relationship_type="alleged",
                    defaults={"notes": ""},
                )
                if created:
                    alleged_migrated += 1
                else:
                    duplicates_skipped += 1

    # Migrate related entities if table exists
    if related_table_exists:
        for case in Case.objects.prefetch_related("related_entities").all():
            for entity in case.related_entities.all():
                relationship, created = CaseEntityRelationship.objects.get_or_create(
                    case=case,
                    entity=entity,
                    relationship_type="related",
                    defaults={"notes": ""},
                )
                if created:
                    related_migrated += 1
                else:
                    duplicates_skipped += 1

    # Log migration results (will appear in migration output)
    print("Migration completed successfully:")
    print(f"  - Alleged entities migrated: {alleged_migrated}")
    print(f"  - Related entities migrated: {related_migrated}")
    print(f"  - Duplicates skipped: {duplicates_skipped}")
    print(f"  - Total relationships created: {alleged_migrated + related_migrated}")

    if not alleged_table_exists and not related_table_exists:
        print(
            "  - No existing data found to migrate (this is normal for new installations)"
        )


def reverse_migration(apps, schema_editor):
    """
    This migration cannot be reversed safely. The original alleged/related
    state cannot be reconstructed once backfilled rows are mixed with
    post-migration data.
    """
    raise IrreversibleError(
        "The CaseEntityRelationship backfill cannot be reversed safely: "
        "the original alleged/related state cannot be reconstructed."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_add_case_entity_relationship"),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_relationships,
            reverse_migration,
            elidable=True,
        ),
    ]
