# Generated by Django 5.2.9 on 2026-03-24

import cases.models
from django.db import migrations, models


def backfill_legacy_uploaded_file(apps, schema_editor):
    DocumentSource = apps.get_model("cases", "DocumentSource")
    DocumentSourceUpload = apps.get_model("cases", "DocumentSourceUpload")

    for source in DocumentSource.objects.exclude(uploaded_file="").exclude(
        uploaded_file__isnull=True
    ):
        file_path = source.uploaded_file.name
        if not file_path:
            continue

        exists = DocumentSourceUpload.objects.filter(
            source_id=source.id,
            file=file_path,
        ).exists()
        if exists:
            continue

        filename = source.uploaded_filename or file_path.split("/")[-1]
        content_type = source.uploaded_content_type or ""

        DocumentSourceUpload.objects.create(
            source_id=source.id,
            file=file_path,
            filename=filename,
            content_type=content_type,
            file_size=source.uploaded_file_size,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_documentsource_uploaded_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSourceUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="jawafdehi/sources/%Y/%m/%d/",
                        validators=[
                            cases.models.validate_upload_file_extension,
                            cases.models.validate_upload_file_size,
                        ],
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename (auto-populated)",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type (auto-populated best-effort)",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes (auto-populated)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Document source this uploaded file belongs to",
                        on_delete=models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="cases.documentsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            backfill_legacy_uploaded_file,
            migrations.RunPython.noop,
        ),
    ]
