# Generated by Django 5.2.9 on 2026-03-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_add_case_entity_relationship"),
        ("cases", "0013_native_file_uploads"),
    ]

    operations = []
