# Generated by Django 5.2.9 on 2026-03-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_merge_20260326_0631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseentityrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("alleged", "Alleged"),
                    ("related", "Related"),
                    ("witness", "Witness"),
                    ("opposition", "Opposition"),
                    ("victim", "Victim"),
                    ("location", "Location"),
                ],
                help_text="Type of relationship between case and entity",
                max_length=20,
            ),
        ),
    ]
