# Generated by Django 5.2.9 on 2026-04-01 20:22

import cases.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_add_accused_relationship_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="bigo",
            field=models.IntegerField(
                blank=True, help_text="Optional numeric bigo value (integer)", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of linked court cases in '<court_identifier>:<case_number>' format",
                validators=[cases.models.validate_court_case_list],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="missing_details",
            field=models.TextField(
                blank=True,
                help_text="Multiline notes describing what details are still missing",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A slug will go in the URL. For CIAA corruption cases, you can prepend the special court case number (e.g. case-case-078-WC-0123-sunil-poudel).",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Slug must be 1-50 characters, can only use letters, numbers, and '-', and cannot start with a digit.",
                        regex="^(?!\\d)[A-Za-z0-9-]{1,50}$",
                    )
                ],
            ),
        ),
    ]
