# Generated by Django 5.2.9 on 2026-03-27 12:00

from django.db import migrations, models
import cases.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_add_accused_relationship_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                db_index=True,
                max_length=50,
                validators=[cases.validators.validate_slug],
                help_text="URL-friendly unique identifier (immutable once set, required for published cases)",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_cases",
            field=models.JSONField(
                default=list,
                blank=True,
                validators=[cases.validators.validate_court_cases],
                help_text="List of court case references in format <court_identifier>:<case_number>",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="missing_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notes about missing or incomplete information for this case",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="bigo",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                help_text="Big integer field for additional case metadata",
            ),
        ),
    ]
