# Generated by Django 5.x
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_add_accused_relationship_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="feedback_attachments/",
                help_text="Optional file attachment (max 10 MB)",
            ),
        ),
    ]
