# Generated by Django 5.2.9 on 2026-03-27 12:00

from django.db import migrations, models
import cases.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_feedback_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                max_length=50,
                validators=[cases.validators.validate_slug],
                help_text="A slug will go in the URL (e.g., jawafdehi.org/case/YOUR-SLUG). For CIAA corruption cases, you can prepend the special court case number (e.g., case-078-WC-0123-sunil-poudel). Must start with a letter and contain only letters, numbers, and hyphens (max 50 characters). Immutable once set, required for published cases.",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_cases",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[cases.validators.validate_court_cases],
                help_text="List of court case references in format {court_identifier}:{case_number}, e.g. ['supreme:078-WC-0123', 'special:076-CR-0456']",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="missing_details",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Notes about missing or incomplete information for this case",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="bigo",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                help_text="Bigo (बिगो) — the total disputed or embezzled amount claimed in the case (in NPR)",
            ),
        ),
    ]
