# Generated by Django 5.2.9 on 2026-04-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_add_slug_court_cases_missing_details_bigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="publication_date",
            field=models.DateField(
                blank=True,
                help_text="Publication date of the source (required for news/media sources)",
                null=True,
            ),
        ),
    ]
