# Generated by Django 5.2.8 on 2025-11-15 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allegation_type",
                    models.CharField(
                        choices=[
                            ("corruption", "Corruption"),
                            ("misconduct", "Misconduct"),
                            ("breach_of_trust", "Breach of Trust"),
                            ("broken_promise", "Broken Promise"),
                            ("media_trial", "Media Trial"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("current", "Current"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("alleged_entities", models.JSONField(default=list)),
                ("related_entities", models.JSONField(default=list)),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField()),
                ("key_allegations", models.TextField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_investigation", "Under Investigation"),
                            ("closed", "Closed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timeline", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_public_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("social_media", "Social Media"),
                            ("media", "Media"),
                            ("crowdsourced", "Crowdsourced"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("related_entity_ids", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("updated", "Updated"),
                            ("response_added", "Response Added"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "allegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="allegations.allegation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_text", models.TextField()),
                ("entity_id", models.CharField(max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="allegations.allegation",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "allegation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="allegations.allegation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="allegations.documentsource",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("allegation", "source")},
            },
        ),
    ]
