# Generated by Django 5.2.8 on 2025-11-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allegations",
            "0002_remove_allegation_timeline_remove_modification_actor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeline",
            name="event",
        ),
        migrations.AddField(
            model_name="timeline",
            name="description",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeline",
            name="title",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
