# Generated by Django 5.2.9 on 2026-03-30 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caseworker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="api_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="auth_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="model",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="summary",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caseworker.skill",
            ),
        ),
    ]
