# Generated by Django 5.2.9 on 2026-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caseworker", "0003_prompt_public_chat_config"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicchatconfig",
            name="knowledge_collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Public knowledge collections exposed to anonymous public chat.",
                related_name="public_chat_configs",
                to="knowledge.knowledgecollection",
            ),
        ),
        migrations.AddField(
            model_name="publicchatconfig",
            name="knowledge_rag_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publicchatconfig",
            name="max_knowledge_results",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
