# Generated by Codex on 2026-05-05

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def populate_provider_profiles(apps, schema_editor):
    LLMProvider = apps.get_model("caseworker", "LLMProvider")
    default_assigned = False
    for provider in LLMProvider.objects.order_by("id"):
        provider.name = f"{provider.provider_type}-{provider.id}"
        provider.display_name = (
            provider.display_name or f"{provider.provider_type} - {provider.model}"
        )
        provider.extra_config = provider.extra_config or {}
        provider.structured_output_mode = provider.structured_output_mode or "auto"
        if provider.is_active and not default_assigned:
            provider.is_default = True
            default_assigned = True
        provider.save(
            update_fields=[
                "name",
                "display_name",
                "extra_config",
                "structured_output_mode",
                "is_default",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("caseworker", "0004_publicchatconfig_knowledge_collections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic Claude"),
                    ("google", "Google Gemini"),
                    ("ollama", "Ollama (Local)"),
                    ("azure", "Azure OpenAI"),
                    ("custom", "Custom"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="llmprovider",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="name",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="base_url",
            field=models.URLField(blank=True, default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="api_version",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="deployment_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="extra_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="llmprovider",
            name="structured_output_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("provider_native", "Provider native"),
                    ("tool_calling", "Tool calling"),
                ],
                default="auto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="publicchatconfig",
            name="classifier_llm_provider",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional classifier provider. Falls back to the answer provider, "
                    "then the default active provider."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_chat_classifier_configs",
                to="caseworker.llmprovider",
            ),
        ),
        migrations.RunPython(populate_provider_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="llmprovider",
            name="name",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name="llmprovider",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True, is_default=True),
                fields=("is_default",),
                name="caseworker_unique_active_default_llm_provider",
            ),
        ),
    ]
