# Generated by Codex on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("caseworker", "0005_llmprovider_profiles_and_classifier_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmprovider",
            options={"ordering": ["-is_default", "name"]},
        ),
        migrations.AlterField(
            model_name="publicchatconfig",
            name="llm_provider",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional answer provider override. Falls back to the default "
                    "active provider."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_chat_configs",
                to="caseworker.llmprovider",
            ),
        ),
    ]
