"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url

load_dotenv()


def get_env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-b&i!8@kw8v+w3%zk)gbsz8^v8w8xjb%l-$!-3x&*pc5hqio02g"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = get_env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")

CSRF_TRUSTED_ORIGINS = get_env_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "tinymce",
    "auditlog",
    "rules.apps.AutodiscoverRulesConfig",
    "cases",
    "nesq",
    "ngm",
    "caseworker",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
    )
}

if os.getenv("NGM_DATABASE_URL"):
    DATABASES["ngm"] = dj_database_url.config(env="NGM_DATABASE_URL")

# Configure connection pooling for PostgreSQL only
if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
    DATABASES["default"]["CONN_MAX_AGE"] = 60
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

if (
    "ngm" in DATABASES
    and DATABASES["ngm"].get("ENGINE") == "django.db.backends.postgresql"
):
    DATABASES["ngm"]["CONN_MAX_AGE"] = 60
    DATABASES["ngm"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise configuration for serving static files
# Configure storage backend - use S3/R2 if AWS credentials are available, otherwise use FileSystemStorage
if os.getenv("AWS_ACCESS_KEY_ID") and os.getenv("AWS_SECRET_ACCESS_KEY"):
    # Use django-storages with S3 backend for both local (Minio) and cloud (R2/AWS S3)
    storage_options = {
        "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
        "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
        "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME", "jawafdehi"),
        "region_name": os.getenv("AWS_S3_REGION_NAME", "auto"),
        "endpoint_url": os.getenv("AWS_S3_ENDPOINT_URL"),
        "use_ssl": os.getenv("AWS_S3_USE_SSL", "True") == "True",
        "querystring_auth": False,  # Generate public URLs (no auth required)
    }

    # Add custom domain for public URLs if specified (separate from endpoint_url for operations)
    if os.getenv("AWS_S3_CUSTOM_DOMAIN"):
        storage_options["custom_domain"] = os.getenv("AWS_S3_CUSTOM_DOMAIN")

    STORAGES = {
        "default": {
            "BACKEND": "cases.storage.HashedFilenameS3Boto3Storage",
            "OPTIONS": storage_options,
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development: use FileSystemStorage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media Files Configuration
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# JWT Configuration


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

# LLM / Caseworker Agent Configuration
CASEWORKER_LLM_PROVIDER = os.getenv("CASEWORKER_LLM_PROVIDER", "anthropic")
CASEWORKER_LLM_MODEL = os.getenv("CASEWORKER_LLM_MODEL", "claude-opus-4-6")
CASEWORKER_LLM_API_KEY = os.getenv("CASEWORKER_LLM_API_KEY", "")

SPECTACULAR_SETTINGS = {
    "TITLE": "Jawafdehi Public Accountability API",
    "DESCRIPTION": """
Public API for the Jawafdehi accountability platform.

This API provides read-only access to published cases of alleged corruption 
and misconduct by public entities in Nepal.

## Features

- **Browse Cases**: List all published cases with filtering and search
- **View Details**: Get complete case information including evidence and timeline
- **Audit History**: Access version history for published cases
- **Document Sources**: Browse evidence sources associated with published cases

## Access

All endpoints are public and do not require authentication. Only published 
cases (state=PUBLISHED) are accessible through this API.

## Filtering & Search

The cases endpoint supports:
- Filtering by case type and tags
- Full-text search across title, description, and key allegations
- Pagination (20 items per page)
    """,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "SERVERS": None,  # Use None to auto-detect from request
    "TAGS": [
        {"name": "cases", "description": "Operations related to accountability cases"},
        {
            "name": "sources",
            "description": "Operations related to document sources and evidence",
        },
    ],
    "ENUM_NAME_OVERRIDES": {
        "CaseTypeEnum": "cases.models.CaseType",
    },
}

# CORS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8080,http://127.0.0.1:8080,https://jawafdehi.org,https://beta.jawafdehi.org",
)
CORS_ALLOWED_ORIGIN_REGEXES = get_env_list("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ALLOW_METHODS = ["GET", "HEAD", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True

# Keep Django's CSRF origin validation aligned with credentialed CORS writes.
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# NES API Configuration
NES_API_URL = os.getenv("NES_API_URL", "https://nes.jawafdehi.org/api")

# NES Database Path - required for GitHub Actions queue processing only.
# Points to the local clone of the nes-db repository.
NES_DB_PATH = os.getenv("NES_DB_PATH")

# NGM Database Configuration (for read-only SQL endpoint)
NGM_QUERY_MAX_ROWS = int(os.getenv("NGM_QUERY_MAX_ROWS", "500"))

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "jawafdehi-cache",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Jawafdehi Admin",
    "site_header": "Jawafdehi",
    "site_brand": "Jawafdehi",
    "site_logo": "corruption-db-logo.png",
    "login_logo": "corruption-db-logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "corruption-db-logo.png",
    "welcome_sign": "Welcome to Jawafdehi Contributor Portal",
    "copyright": "Jawafdehi",
    "search_model": ["cases.Case", "cases.DocumentSource"],
    "user_avatar": None,
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Public API", "url": "/api/swagger", "new_window": True},
    ],
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["cases", "auth"],
    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cases.Case": "fas fa-gavel",
        "cases.DocumentSource": "fas fa-file-alt",
    },
    # UI Tweaks
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 800,
    "width": "100%",
    "menubar": True,
    "browser_spellcheck": True,
    "plugins": "advlist,autolink,lists,link,image,charmap,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,"
    "help,wordcount",
    "toolbar": "undo redo | blocks | "
    "bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | bullist numlist outdent indent | "
    "removeformat | code | help",
    "license_key": "gpl",
}
