# Generated by Django 5.2.9 on 2025-12-18 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedEntityChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(help_text="NES entity type", max_length=20),
                ),
                (
                    "entity_sub_type",
                    models.CharField(
                        blank=True, help_text="NES entity sub-type", max_length=50
                    ),
                ),
                (
                    "nes_entity_id",
                    models.CharField(
                        blank=True,
                        help_text="NES entity ID for updates",
                        max_length=300,
                    ),
                ),
                (
                    "entity_data",
                    models.JSONField(help_text="Complete entity data for NES"),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the change"),
                ),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved Entity Change",
                "verbose_name_plural": "Approved Entity Changes",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredExtractionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document", models.FileField(upload_to="agni/documents/")),
                (
                    "session_data",
                    models.JSONField(
                        default=dict,
                        help_text="Serialized AgniExtractionSession data (includes guidance)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("awaiting_review", "Awaiting Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extraction Session",
                "verbose_name_plural": "Extraction Sessions",
                "ordering": ["-updated_at"],
            },
        ),
    ]
