# Generated by Django 5.2.9 on 2025-12-18 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadDocument",
            fields=[],
            options={
                "verbose_name": "Upload Document",
                "verbose_name_plural": "Upload Document",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("agni.storedextractionsession",),
        ),
        migrations.AddField(
            model_name="storedextractionsession",
            name="active_tasks",
            field=models.JSONField(
                default=list,
                help_text="Currently running tasks as list of ActiveTask objects",
            ),
        ),
        migrations.AddField(
            model_name="storedextractionsession",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if processing failed"
            ),
        ),
        migrations.AddField(
            model_name="storedextractionsession",
            name="progress_info",
            field=models.JSONField(
                default=dict, help_text="Progress tracking information"
            ),
        ),
        migrations.AlterField(
            model_name="storedextractionsession",
            name="session_data",
            field=models.JSONField(
                default=dict, help_text="Serialized AgniExtractionSession data"
            ),
        ),
        migrations.AlterField(
            model_name="storedextractionsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing_metadata", "Processing Metadata"),
                    ("metadata_extracted", "Metadata Extracted"),
                    ("processing_entities", "Processing Entities"),
                    ("awaiting_review", "Awaiting Review"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="SessionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("extract_metadata", "Extract Metadata"),
                            ("extract_entities", "Extract Entities"),
                            ("update_entity", "Update Individual Entity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(help_text="Django Q task ID", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "entity_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Entity index for UPDATE_ENTITY tasks",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="agni.storedextractionsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Task",
                "verbose_name_plural": "Session Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "task_type"],
                        name="agni_sessio_session_38c595_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="agni_sessio_task_id_353866_idx"
                    ),
                    models.Index(
                        fields=["status"], name="agni_sessio_status_fd294e_idx"
                    ),
                ],
            },
        ),
    ]
