# Generated by Cursor on 2025-12-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agni", "0002_uploaddocument_storedextractionsession_active_tasks_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SessionTask",
        ),
    ]


