# Generated by Django 5.2.9 on 2025-12-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agni", "0003_delete_sessiontask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedextractionsession",
            name="active_tasks",
            field=models.JSONField(
                default=list,
                help_text="Currently running tasks as list of AgniBackgroundTask objects",
            ),
        ),
    ]
