# Generated by Cursor on 2025-12-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agni", "0004_alter_storedextractionsession_active_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storedextractionsession",
            old_name="active_tasks",
            new_name="tasks",
        ),
    ]


